#version 450

layout (local_size_x = 32) in;

struct Vertex {
	vec3 pos;
	vec3 color;
	vec3 normal;
	vec3 tangent;
	vec2 texCoord;
	vec3 speed;
	float movable;
};

layout(std430, binding = 0) buffer vertexBlock {
	Vertex vertices[];
};

struct Constraint {
	int A;
	int B;
	float length;
};

layout(std430, binding = 1) buffer constraintBlock {
	Constraint constraints[];
};

void main() {
	uint index = gl_GlobalInvocationID.x;

	vertices[index].pos += vec3(0, 0, +0.0001);
}